// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	nft "Nft-Go/nft/http/internal/handler/nft"
	"Nft-Go/nft/http/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RateLimitMiddleware, serverCtx.JwtMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/nft/BuyFromPool",
					Handler: nft.BuyFromPoolHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/nft/CreateActivity",
					Handler: nft.CreateActivityHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/nft/CreatePool",
					Handler: nft.CreatePoolHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/nft/GetActivityPages",
					Handler: nft.GetActivityPagesHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/nft/GetDcById",
					Handler: nft.GetDcByIdHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/nft/GetDcFromActivity",
					Handler: nft.GetDcFromActivityHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/nft/GetDcHistory",
					Handler: nft.GetDcHistoryHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/nft/GetDcPages",
					Handler: nft.GetDcPagesHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/nft/GetMessageByAddressOrHash",
					Handler: nft.GetMessageByAddressOrHashHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/nft/GetMyDc",
					Handler: nft.GetMyDcHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/nft/GetMyPool",
					Handler: nft.GetMyPoolHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/nft/GetOneActivity",
					Handler: nft.GetOneActivityHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/nft/GetPoolById",
					Handler: nft.GetPoolByIdHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/nft/GetPoolPages",
					Handler: nft.GetPoolPagesHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/nft/GiveDc",
					Handler: nft.GiveDcHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/nft/SearchActivities",
					Handler: nft.SearchActivitiesHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/nft/SelectDc",
					Handler: nft.SelectDcHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/nft/SelectPool",
					Handler: nft.SelectPoolHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/v1"),
	)
}
