// Code generated by goctl. DO NOT EDIT.
// Source: nft.proto

package server

import (
	nft2 "Nft-Go/common/api/nft"
	"context"

	"Nft-Go/nft/internal/logic"
	"Nft-Go/nft/internal/svc"
)

type NftServer struct {
	svcCtx *svc.ServiceContext
	nft2.UnimplementedNftServer
}

func NewNftServer(svcCtx *svc.ServiceContext) *NftServer {
	return &NftServer{
		svcCtx: svcCtx,
	}
}

func (s *NftServer) GetMessageByUserAddress(ctx context.Context, in *nft2.GetMessageByUserAddressRequest) (*nft2.GetMessageByUserAddressDTO, error) {
	l := logic.NewGetMessageByUserAddressLogic(ctx, s.svcCtx)
	return l.GetMessageByUserAddress(in)
}

func (s *NftServer) CreateActivity(ctx context.Context, in *nft2.CreateActivityRequest) (*nft2.Response, error) {
	l := logic.NewCreateActivityLogic(ctx, s.svcCtx)
	return l.CreateActivity(in)
}

func (s *NftServer) PrizeDcFromActivity(ctx context.Context, in *nft2.GetDcFromActivityRequest) (*nft2.Response, error) {
	l := logic.NewPrizeDcFromActivityLogic(ctx, s.svcCtx)
	return l.PrizeDcFromActivity(in)
}

func (s *NftServer) GetAllActivity(ctx context.Context, in *nft2.Empty) (*nft2.ActivityPageVOList, error) {
	l := logic.NewGetAllActivityLogic(ctx, s.svcCtx)
	return l.GetAllActivity(in)
}

func (s *NftServer) GetOneActivity(ctx context.Context, in *nft2.GetOneActivityRequest) (*nft2.ActivityDetailsVO, error) {
	l := logic.NewGetOneActivityLogic(ctx, s.svcCtx)
	return l.GetOneActivity(in)
}

func (s *NftServer) SearchActivities(ctx context.Context, in *nft2.SearchActivitiesRequest) (*nft2.ActivityPageVOList, error) {
	l := logic.NewSearchActivitiesLogic(ctx, s.svcCtx)
	return l.SearchActivities(in)
}

func (s *NftServer) GiveDc(ctx context.Context, in *nft2.GiveDcRequest) (*nft2.Response, error) {
	l := logic.NewGiveDcLogic(ctx, s.svcCtx)
	return l.GiveDc(in)
}

func (s *NftServer) GetAllDc(ctx context.Context, in *nft2.Empty) (*nft2.DcPageVOList, error) {
	l := logic.NewGetAllDcLogic(ctx, s.svcCtx)
	return l.GetAllDc(in)
}

func (s *NftServer) SelectDc(ctx context.Context, in *nft2.SelectDcRequest) (*nft2.DcPageVOList, error) {
	l := logic.NewSelectDcLogic(ctx, s.svcCtx)
	return l.SelectDc(in)
}

func (s *NftServer) GetDcById(ctx context.Context, in *nft2.GetDcByIdRequest) (*nft2.DcDetailVO, error) {
	l := logic.NewGetDcByIdLogic(ctx, s.svcCtx)
	return l.GetDcById(in)
}

func (s *NftServer) GetMyDc(ctx context.Context, in *nft2.Empty) (*nft2.DcPageVOList, error) {
	l := logic.NewGetMyDcLogic(ctx, s.svcCtx)
	return l.GetMyDc(in)
}

func (s *NftServer) GetDcHistory(ctx context.Context, in *nft2.GetDcHistoryRequest) (*nft2.CollectionMessageOnChainVO, error) {
	l := logic.NewGetDcHistoryLogic(ctx, s.svcCtx)
	return l.GetDcHistory(in)
}

func (s *NftServer) CreatePool(ctx context.Context, in *nft2.CreatePoolRequest) (*nft2.Response, error) {
	l := logic.NewCreatePoolLogic(ctx, s.svcCtx)
	return l.CreatePool(in)
}

func (s *NftServer) BuyFromPool(ctx context.Context, in *nft2.BuyFromPoolRequest) (*nft2.Response, error) {
	l := logic.NewBuyFromPoolLogic(ctx, s.svcCtx)
	return l.BuyFromPool(in)
}

func (s *NftServer) SelectPool(ctx context.Context, in *nft2.SelectPoolRequest) (*nft2.PoolPageVOList, error) {
	l := logic.NewSelectPoolLogic(ctx, s.svcCtx)
	return l.SelectPool(in)
}

func (s *NftServer) GetPoolById(ctx context.Context, in *nft2.GetPoolByIdRequest) (*nft2.PoolDetailsVO, error) {
	l := logic.NewGetPoolByIdLogic(ctx, s.svcCtx)
	return l.GetPoolById(in)
}

func (s *NftServer) GetAllPool(ctx context.Context, in *nft2.Empty) (*nft2.PoolPageVOList, error) {
	l := logic.NewGetAllPoolLogic(ctx, s.svcCtx)
	return l.GetAllPool(in)
}

func (s *NftServer) GetMyPool(ctx context.Context, in *nft2.Empty) (*nft2.PoolPageVOList, error) {
	l := logic.NewGetMyPoolLogic(ctx, s.svcCtx)
	return l.GetMyPool(in)
}
