// Code generated by goctl. DO NOT EDIT.
package types

type AccountMessageVO struct {
	Hash             string         `json:"hash"`
	RegisterTime     string         `json:"registerTime"`
	OwnedCollections []DcOverviewVO `json:"ownedCollections"`
}

type ActivityDetailsVO struct {
	Id                  int32  `json:"id"`
	ActivityName        string `json:"activityName"`
	ActivityDescription string `json:"activityDescription"`
	DcName              string `json:"dcName"`
	DcDescription       string `json:"dcDescription"`
	Cid                 string `json:"cid"`
	HostName            string `json:"hostName"`
	HostAddress         string `json:"hostAddress"`
	Amount              int32  `json:"amount"`
	Left                int32  `json:"left"`
	ContractAddress     string `json:"contractAddress"`
}

type ActivityPageVO struct {
	Id          int32  `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Cid         string `json:"cid"`
	HostName    string `json:"hostName"`
	HostAddress string `json:"hostAddress"`
	Amount      int32  `json:"amount"`
	Left        int32  `json:"left"`
}

type ActivityPageVOList struct {
	ActivityPageVO []ActivityPageVO `json:"activityPageVO"`
}

type BuyFromPoolRequest struct {
	PoolId int32 `json:"poolId"`
}

type CollectionMessageOnChainVO struct {
	Name            string        `json:"name"`
	Hash            string        `json:"hash"`
	Description     string        `json:"description"`
	CreatorAddress  string        `json:"creatorAddress"`
	OwnerAddress    string        `json:"ownerAddress"`
	TraceBackVOList []TraceBackVO `json:"traceBackVOList"`
}

type CommonResponse struct {
	Code    int    `json:"code"`
	Data    string `json:"data"`
	Message string `json:"message"`
}

type CreateActivityRequest struct {
	Name          string `json:"name"`
	Description   string `json:"description"`
	Password      string `json:"password"`
	Amount        int32  `json:"amount"`
	DcName        string `json:"dcName"`
	DcDescription string `json:"dcDescription"`
	Cid           string `json:"cid"`
}

type CreatePoolRequest struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Status      bool   `json:"status"`
	Price       int32  `json:"price"`
	Amount      int32  `json:"amount"`
	LimitAmount int32  `json:"limitAmount"`
	Cid         string `json:"cid"`
	Creator     string `json:"creator"`
}

type DcDetailVO struct {
	DcId            int32  `json:"dcId"`
	Hash            string `json:"hash"`
	Cid             string `json:"Cid"`
	Name            string `json:"name"`
	Description     string `json:"description"`
	Price           int32  `json:"price"`
	CreatorName     string `json:"creatorName"`
	CreatorAddress  string `json:"creatorAddress"`
	OwnerName       string `json:"ownerName"`
	OwnerAddress    string `json:"ownerAddress"`
	ContractAddress string `json:"contractAddress"`
}

type DcOverviewVO struct {
	Id      int32  `json:"id"`
	Hash    string `json:"hash"`
	GetTime string `json:"getTime"`
}

type DcPageVO struct {
	Cid         string `json:"Cid"`
	Name        string `json:"name"`
	DcId        int32  `json:"dcId"`
	Hash        string `json:"hash"`
	CreatorName string `json:"creatorName"`
	Price       int32  `json:"price"`
}

type DcPageVOList struct {
	DcPageVO []DcPageVO `json:"dcPageVO"`
}

type GetDcByIdRequest struct {
	Id int32 `json:"id"`
}

type GetDcFromActivityRequest struct {
	Id       int32  `json:"id"`
	Password string `json:"password"`
}

type GetDigitalCollectionHistoryRequest struct {
	Id int32 `json:"id"`
}

type GetMessageByAddressOrHashRequest struct {
	Hash string `json:"hash"`
}

type GetMessageByHashDTO struct {
	Type                       int32                      `json:"type"`
	AccountMessageVO           AccountMessageVO           `json:"accountMessageVO"`
	CollectionMessageOnChainVO CollectionMessageOnChainVO `json:"collectionMessageOnChainVO"`
}

type GetOneActivityRequest struct {
	Id int32 `json:"id"`
}

type GetPoolByIdRequest struct {
	Id int32 `json:"id"`
}

type GiveDcRequest struct {
	ToName    string `json:"toName"`
	ToAddress string `json:"toAddress"`
	DcId      int32  `json:"dcId"`
}

type IdNoticeRequest struct {
	Id string `json:"id"`
}

type LoginRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type PoolDetailsVO struct {
	PoolId          int32  `json:"poolId"`
	Name            string `json:"name"`
	Description     string `json:"description"`
	Cid             string `json:"Cid"`
	Price           int32  `json:"price"`
	Amount          int32  `json:"amount"`
	Left            int32  `json:"left"`
	CreatorName     string `json:"creatorName"`
	CreatorAddress  string `json:"creatorAddress"`
	ContractAddress string `json:"contractAddress"`
}

type PoolPageVO struct {
	PoolId      int32  `json:"poolId"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Cid         string `json:"Cid"`
	CreatorName string `json:"creatorName"`
	Status      bool   `json:"status"`
	SoldOut     bool   `json:"soldOut"`
	Price       int32  `json:"price"`
}

type PoolPageVOList struct {
	PoolPageVO []PoolPageVO `json:"poolPageVO"`
}

type RegisterRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Email    string `json:"email"`
	Avatar   string `json:"avatar"`
}

type SearchActivitiesRequest struct {
	HostName     string `json:"hostName"`
	ActivityName string `json:"activityName"`
}

type SelectDcRequest struct {
	Name string `json:"name"`
}

type SelectPoolRequest struct {
	Name        string `json:"name"`
	CreatorName string `json:"creatorName"`
	MinPrice    int32  `json:"minPrice"`
	MaxPrice    int32  `json:"maxPrice"`
}

type TitleNoticeRequest struct {
	Title string `json:"title"`
}

type TraceBackVO struct {
	FromAddress  string `json:"fromAddress"`
	ToAddress    string `json:"toAddress"`
	TransferType string `json:"transferType"`
	TransferTime string `json:"transferTime"`
}

type UploadRequest struct {
	File string `json:"file"`
}

type UserNameRequest struct {
	Username string `json:"username"`
}
