// Code generated by goctl. DO NOT EDIT.
package types

type CommonResponse struct {
	Code    int    `json:"code"`
	Data    string `json:"data"`
	Message string `json:"message"`
}

type IdNoticeRequest struct {
	Id string `json:"id"`
}

type LoginRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type RegisterRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Email    string `json:"email"`
	Avatar   string `json:"avatar"`
}

type TitleNoticeRequest struct {
	Title string `json:"title"`
}

type UploadRequest struct {
	File string `json:"file"`
}

type UserNameRequest struct {
	Username string `json:"username"`
}
