// Code generated by goctl. DO NOT EDIT.
// Source: nft.proto

package server

import (
	"Nft-Go/common/api/nft"
	"context"

	"Nft-Go/nft/internal/logic"
	"Nft-Go/nft/internal/svc"
)

type NftServer struct {
	svcCtx *svc.ServiceContext
	nft.UnimplementedNftServer
}

func NewNftServer(svcCtx *svc.ServiceContext) *NftServer {
	return &NftServer{
		svcCtx: svcCtx,
	}
}

func (s *NftServer) GetMessageByAddressOrHash(ctx context.Context, in *nft.GetMessageByAddressOrHashRequest) (*nft.GetMessageByAddressOrHashDTO, error) {
	l := logic.NewGetMessageByAddressOrHashLogic(ctx, s.svcCtx)
	return l.GetMessageByAddressOrHash(in)
}

func (s *NftServer) CreateActivity(ctx context.Context, in *nft.CreateActivityRequest) (*nft.Response, error) {
	l := logic.NewCreateActivityLogic(ctx, s.svcCtx)
	return l.CreateActivity(in)
}

func (s *NftServer) PrizeDcFromActivity(ctx context.Context, in *nft.GetDcFromActivityRequest) (*nft.Response, error) {
	l := logic.NewPrizeDcFromActivityLogic(ctx, s.svcCtx)
	return l.PrizeDcFromActivity(in)
}

func (s *NftServer) GetActivityPages(ctx context.Context, in *nft.PageRequest) (*nft.ActivityPageVOList, error) {
	l := logic.NewGetActivityPagesLogic(ctx, s.svcCtx)
	return l.GetActivityPages(in)
}

func (s *NftServer) GetDcPages(ctx context.Context, in *nft.PageRequest) (*nft.DcPageVOList, error) {
	l := logic.NewGetDcPagesLogic(ctx, s.svcCtx)
	return l.GetDcPages(in)
}

func (s *NftServer) GetPoolPages(ctx context.Context, in *nft.PageRequest) (*nft.PoolPageVOList, error) {
	l := logic.NewGetPoolPagesLogic(ctx, s.svcCtx)
	return l.GetPoolPages(in)
}

func (s *NftServer) GetOneActivity(ctx context.Context, in *nft.GetOneActivityRequest) (*nft.ActivityDetailsVO, error) {
	l := logic.NewGetOneActivityLogic(ctx, s.svcCtx)
	return l.GetOneActivity(in)
}

func (s *NftServer) SearchActivities(ctx context.Context, in *nft.SearchActivitiesRequest) (*nft.ActivityPageVOList, error) {
	l := logic.NewSearchActivitiesLogic(ctx, s.svcCtx)
	return l.SearchActivities(in)
}

func (s *NftServer) GiveDc(ctx context.Context, in *nft.GiveDcRequest) (*nft.Response, error) {
	l := logic.NewGiveDcLogic(ctx, s.svcCtx)
	return l.GiveDc(in)
}

func (s *NftServer) SelectDc(ctx context.Context, in *nft.SelectDcRequest) (*nft.DcPageVOList, error) {
	l := logic.NewSelectDcLogic(ctx, s.svcCtx)
	return l.SelectDc(in)
}

func (s *NftServer) GetDcById(ctx context.Context, in *nft.GetDcByIdRequest) (*nft.DcDetailVO, error) {
	l := logic.NewGetDcByIdLogic(ctx, s.svcCtx)
	return l.GetDcById(in)
}

func (s *NftServer) GetMyDc(ctx context.Context, in *nft.Empty) (*nft.DcPageVOList, error) {
	l := logic.NewGetMyDcLogic(ctx, s.svcCtx)
	return l.GetMyDc(in)
}

func (s *NftServer) GetDcHistory(ctx context.Context, in *nft.GetDcHistoryRequest) (*nft.CollectionMessageOnChainVO, error) {
	l := logic.NewGetDcHistoryLogic(ctx, s.svcCtx)
	return l.GetDcHistory(in)
}

func (s *NftServer) CreatePool(ctx context.Context, in *nft.CreatePoolRequest) (*nft.Response, error) {
	l := logic.NewCreatePoolLogic(ctx, s.svcCtx)
	return l.CreatePool(in)
}

func (s *NftServer) BuyFromPool(ctx context.Context, in *nft.BuyFromPoolRequest) (*nft.Response, error) {
	l := logic.NewBuyFromPoolLogic(ctx, s.svcCtx)
	return l.BuyFromPool(in)
}

func (s *NftServer) SelectPool(ctx context.Context, in *nft.SelectPoolRequest) (*nft.PoolPageVOList, error) {
	l := logic.NewSelectPoolLogic(ctx, s.svcCtx)
	return l.SelectPool(in)
}

func (s *NftServer) GetPoolById(ctx context.Context, in *nft.GetPoolByIdRequest) (*nft.PoolDetailsVO, error) {
	l := logic.NewGetPoolByIdLogic(ctx, s.svcCtx)
	return l.GetPoolById(in)
}

func (s *NftServer) GetMyPool(ctx context.Context, in *nft.Empty) (*nft.PoolPageVOList, error) {
	l := logic.NewGetMyPoolLogic(ctx, s.svcCtx)
	return l.GetMyPool(in)
}
