// EDIT IT, change to your package, service and message

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.25.3
// source: blc.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SignUpResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PrivateKey string `protobuf:"bytes,1,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	Address    string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *SignUpResponse) Reset() {
	*x = SignUpResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignUpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignUpResponse) ProtoMessage() {}

func (x *SignUpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignUpResponse.ProtoReflect.Descriptor instead.
func (*SignUpResponse) Descriptor() ([]byte, []int) {
	return file_blc_proto_rawDescGZIP(), []int{0}
}

func (x *SignUpResponse) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

func (x *SignUpResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type UserBalanceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *UserBalanceRequest) Reset() {
	*x = UserBalanceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserBalanceRequest) ProtoMessage() {}

func (x *UserBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserBalanceRequest.ProtoReflect.Descriptor instead.
func (*UserBalanceRequest) Descriptor() ([]byte, []int) {
	return file_blc_proto_rawDescGZIP(), []int{1}
}

func (x *UserBalanceRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type UserBalanceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Balance string `protobuf:"bytes,1,opt,name=balance,proto3" json:"balance,omitempty"`
}

func (x *UserBalanceResponse) Reset() {
	*x = UserBalanceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserBalanceResponse) ProtoMessage() {}

func (x *UserBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserBalanceResponse.ProtoReflect.Descriptor instead.
func (*UserBalanceResponse) Descriptor() ([]byte, []int) {
	return file_blc_proto_rawDescGZIP(), []int{2}
}

func (x *UserBalanceResponse) GetBalance() string {
	if x != nil {
		return x.Balance
	}
	return ""
}

type ActivityAmountResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Amount int32 `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *ActivityAmountResponse) Reset() {
	*x = ActivityAmountResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActivityAmountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityAmountResponse) ProtoMessage() {}

func (x *ActivityAmountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityAmountResponse.ProtoReflect.Descriptor instead.
func (*ActivityAmountResponse) Descriptor() ([]byte, []int) {
	return file_blc_proto_rawDescGZIP(), []int{3}
}

func (x *ActivityAmountResponse) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type CreateActivityRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserKey *UserKey           `protobuf:"bytes,1,opt,name=user_key,json=userKey,proto3" json:"user_key,omitempty"`
	Args    *CreateActivityDTO `protobuf:"bytes,2,opt,name=args,proto3" json:"args,omitempty"`
}

func (x *CreateActivityRequest) Reset() {
	*x = CreateActivityRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateActivityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateActivityRequest) ProtoMessage() {}

func (x *CreateActivityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateActivityRequest.ProtoReflect.Descriptor instead.
func (*CreateActivityRequest) Descriptor() ([]byte, []int) {
	return file_blc_proto_rawDescGZIP(), []int{4}
}

func (x *CreateActivityRequest) GetUserKey() *UserKey {
	if x != nil {
		return x.UserKey
	}
	return nil
}

func (x *CreateActivityRequest) GetArgs() *CreateActivityDTO {
	if x != nil {
		return x.Args
	}
	return nil
}

type GetIdToActivityRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetIdToActivityRequest) Reset() {
	*x = GetIdToActivityRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blc_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetIdToActivityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIdToActivityRequest) ProtoMessage() {}

func (x *GetIdToActivityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blc_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIdToActivityRequest.ProtoReflect.Descriptor instead.
func (*GetIdToActivityRequest) Descriptor() ([]byte, []int) {
	return file_blc_proto_rawDescGZIP(), []int{5}
}

func (x *GetIdToActivityRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type BeforeMintRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *BeforeMintRequest) Reset() {
	*x = BeforeMintRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blc_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BeforeMintRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeforeMintRequest) ProtoMessage() {}

func (x *BeforeMintRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blc_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeforeMintRequest.ProtoReflect.Descriptor instead.
func (*BeforeMintRequest) Descriptor() ([]byte, []int) {
	return file_blc_proto_rawDescGZIP(), []int{6}
}

func (x *BeforeMintRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetDcFromActivityRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key  *UserKey              `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Args *GetDcFromActivityDTO `protobuf:"bytes,2,opt,name=args,proto3" json:"args,omitempty"`
}

func (x *GetDcFromActivityRequest) Reset() {
	*x = GetDcFromActivityRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blc_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDcFromActivityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDcFromActivityRequest) ProtoMessage() {}

func (x *GetDcFromActivityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blc_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDcFromActivityRequest.ProtoReflect.Descriptor instead.
func (*GetDcFromActivityRequest) Descriptor() ([]byte, []int) {
	return file_blc_proto_rawDescGZIP(), []int{7}
}

func (x *GetDcFromActivityRequest) GetKey() *UserKey {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *GetDcFromActivityRequest) GetArgs() *GetDcFromActivityDTO {
	if x != nil {
		return x.Args
	}
	return nil
}

type GetUserStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hash string `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (x *GetUserStatusRequest) Reset() {
	*x = GetUserStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blc_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserStatusRequest) ProtoMessage() {}

func (x *GetUserStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blc_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserStatusRequest.ProtoReflect.Descriptor instead.
func (*GetUserStatusRequest) Descriptor() ([]byte, []int) {
	return file_blc_proto_rawDescGZIP(), []int{8}
}

func (x *GetUserStatusRequest) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type UserStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int64 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *UserStatusResponse) Reset() {
	*x = UserStatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blc_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserStatusResponse) ProtoMessage() {}

func (x *UserStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blc_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserStatusResponse.ProtoReflect.Descriptor instead.
func (*UserStatusResponse) Descriptor() ([]byte, []int) {
	return file_blc_proto_rawDescGZIP(), []int{9}
}

func (x *UserStatusResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type CheckDcAndReturnTimeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dto *CheckDcAndReturnTimeDTO `protobuf:"bytes,1,opt,name=dto,proto3" json:"dto,omitempty"`
}

func (x *CheckDcAndReturnTimeRequest) Reset() {
	*x = CheckDcAndReturnTimeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blc_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckDcAndReturnTimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckDcAndReturnTimeRequest) ProtoMessage() {}

func (x *CheckDcAndReturnTimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blc_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckDcAndReturnTimeRequest.ProtoReflect.Descriptor instead.
func (*CheckDcAndReturnTimeRequest) Descriptor() ([]byte, []int) {
	return file_blc_proto_rawDescGZIP(), []int{10}
}

func (x *CheckDcAndReturnTimeRequest) GetDto() *CheckDcAndReturnTimeDTO {
	if x != nil {
		return x.Dto
	}
	return nil
}

type GetHashToDcIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hash []byte `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (x *GetHashToDcIdRequest) Reset() {
	*x = GetHashToDcIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blc_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHashToDcIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHashToDcIdRequest) ProtoMessage() {}

func (x *GetHashToDcIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blc_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHashToDcIdRequest.ProtoReflect.Descriptor instead.
func (*GetHashToDcIdRequest) Descriptor() ([]byte, []int) {
	return file_blc_proto_rawDescGZIP(), []int{11}
}

func (x *GetHashToDcIdRequest) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

type GetHashToDcIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DcId int32 `protobuf:"varint,1,opt,name=dc_id,json=dcId,proto3" json:"dc_id,omitempty"`
}

func (x *GetHashToDcIdResponse) Reset() {
	*x = GetHashToDcIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blc_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHashToDcIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHashToDcIdResponse) ProtoMessage() {}

func (x *GetHashToDcIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blc_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHashToDcIdResponse.ProtoReflect.Descriptor instead.
func (*GetHashToDcIdResponse) Descriptor() ([]byte, []int) {
	return file_blc_proto_rawDescGZIP(), []int{12}
}

func (x *GetHashToDcIdResponse) GetDcId() int32 {
	if x != nil {
		return x.DcId
	}
	return 0
}

type GiveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GiveDTO *GiveDTO `protobuf:"bytes,1,opt,name=giveDTO,proto3" json:"giveDTO,omitempty"`
}

func (x *GiveRequest) Reset() {
	*x = GiveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blc_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GiveRequest) ProtoMessage() {}

func (x *GiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blc_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GiveRequest.ProtoReflect.Descriptor instead.
func (*GiveRequest) Descriptor() ([]byte, []int) {
	return file_blc_proto_rawDescGZIP(), []int{13}
}

func (x *GiveRequest) GetGiveDTO() *GiveDTO {
	if x != nil {
		return x.GiveDTO
	}
	return nil
}

type GetDcHistoryAndMessageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetDcHistoryAndMessageRequest) Reset() {
	*x = GetDcHistoryAndMessageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blc_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDcHistoryAndMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDcHistoryAndMessageRequest) ProtoMessage() {}

func (x *GetDcHistoryAndMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blc_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDcHistoryAndMessageRequest.ProtoReflect.Descriptor instead.
func (*GetDcHistoryAndMessageRequest) Descriptor() ([]byte, []int) {
	return file_blc_proto_rawDescGZIP(), []int{14}
}

func (x *GetDcHistoryAndMessageRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type PoolAmountResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Amount int32 `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *PoolAmountResponse) Reset() {
	*x = PoolAmountResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blc_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PoolAmountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolAmountResponse) ProtoMessage() {}

func (x *PoolAmountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blc_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolAmountResponse.ProtoReflect.Descriptor instead.
func (*PoolAmountResponse) Descriptor() ([]byte, []int) {
	return file_blc_proto_rawDescGZIP(), []int{15}
}

func (x *PoolAmountResponse) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type CreatePoolRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserKey *UserKey       `protobuf:"bytes,1,opt,name=user_key,json=userKey,proto3" json:"user_key,omitempty"`
	Dto     *CreatePoolDTO `protobuf:"bytes,2,opt,name=dto,proto3" json:"dto,omitempty"`
}

func (x *CreatePoolRequest) Reset() {
	*x = CreatePoolRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blc_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePoolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePoolRequest) ProtoMessage() {}

func (x *CreatePoolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blc_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePoolRequest.ProtoReflect.Descriptor instead.
func (*CreatePoolRequest) Descriptor() ([]byte, []int) {
	return file_blc_proto_rawDescGZIP(), []int{16}
}

func (x *CreatePoolRequest) GetUserKey() *UserKey {
	if x != nil {
		return x.UserKey
	}
	return nil
}

func (x *CreatePoolRequest) GetDto() *CreatePoolDTO {
	if x != nil {
		return x.Dto
	}
	return nil
}

type MintRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserKey *UserKey `protobuf:"bytes,1,opt,name=user_key,json=userKey,proto3" json:"user_key,omitempty"`
	PoolId  int32    `protobuf:"varint,2,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
}

func (x *MintRequest) Reset() {
	*x = MintRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blc_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MintRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MintRequest) ProtoMessage() {}

func (x *MintRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blc_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MintRequest.ProtoReflect.Descriptor instead.
func (*MintRequest) Descriptor() ([]byte, []int) {
	return file_blc_proto_rawDescGZIP(), []int{17}
}

func (x *MintRequest) GetUserKey() *UserKey {
	if x != nil {
		return x.UserKey
	}
	return nil
}

func (x *MintRequest) GetPoolId() int32 {
	if x != nil {
		return x.PoolId
	}
	return 0
}

type UserKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserKey string `protobuf:"bytes,1,opt,name=user_key,json=userKey,proto3" json:"user_key,omitempty"`
}

func (x *UserKey) Reset() {
	*x = UserKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blc_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserKey) ProtoMessage() {}

func (x *UserKey) ProtoReflect() protoreflect.Message {
	mi := &file_blc_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserKey.ProtoReflect.Descriptor instead.
func (*UserKey) Descriptor() ([]byte, []int) {
	return file_blc_proto_rawDescGZIP(), []int{18}
}

func (x *UserKey) GetUserKey() string {
	if x != nil {
		return x.UserKey
	}
	return ""
}

type GiveDTO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ToAddress string `protobuf:"bytes,1,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`
	DcId      int32  `protobuf:"varint,2,opt,name=dc_id,json=dcId,proto3" json:"dc_id,omitempty"`
}

func (x *GiveDTO) Reset() {
	*x = GiveDTO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blc_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GiveDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GiveDTO) ProtoMessage() {}

func (x *GiveDTO) ProtoReflect() protoreflect.Message {
	mi := &file_blc_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GiveDTO.ProtoReflect.Descriptor instead.
func (*GiveDTO) Descriptor() ([]byte, []int) {
	return file_blc_proto_rawDescGZIP(), []int{19}
}

func (x *GiveDTO) GetToAddress() string {
	if x != nil {
		return x.ToAddress
	}
	return ""
}

func (x *GiveDTO) GetDcId() int32 {
	if x != nil {
		return x.DcId
	}
	return 0
}

type GetDcFromActivityDTO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActivityId int64  `protobuf:"varint,1,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	Password   []byte `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *GetDcFromActivityDTO) Reset() {
	*x = GetDcFromActivityDTO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blc_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDcFromActivityDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDcFromActivityDTO) ProtoMessage() {}

func (x *GetDcFromActivityDTO) ProtoReflect() protoreflect.Message {
	mi := &file_blc_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDcFromActivityDTO.ProtoReflect.Descriptor instead.
func (*GetDcFromActivityDTO) Descriptor() ([]byte, []int) {
	return file_blc_proto_rawDescGZIP(), []int{20}
}

func (x *GetDcFromActivityDTO) GetActivityId() int64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *GetDcFromActivityDTO) GetPassword() []byte {
	if x != nil {
		return x.Password
	}
	return nil
}

type DcHistoryAndMessageOutputDTO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Args           []*TraceStruct `protobuf:"bytes,1,rep,name=args,proto3" json:"args,omitempty"`
	Hash           []byte         `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	CreatorAddress string         `protobuf:"bytes,3,opt,name=creator_address,json=creatorAddress,proto3" json:"creator_address,omitempty"`
	OwnerAddress   string         `protobuf:"bytes,4,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	DcName         string         `protobuf:"bytes,5,opt,name=dc_name,json=dcName,proto3" json:"dc_name,omitempty"`
	PoolId         int64          `protobuf:"varint,6,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
}

func (x *DcHistoryAndMessageOutputDTO) Reset() {
	*x = DcHistoryAndMessageOutputDTO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blc_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DcHistoryAndMessageOutputDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DcHistoryAndMessageOutputDTO) ProtoMessage() {}

func (x *DcHistoryAndMessageOutputDTO) ProtoReflect() protoreflect.Message {
	mi := &file_blc_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DcHistoryAndMessageOutputDTO.ProtoReflect.Descriptor instead.
func (*DcHistoryAndMessageOutputDTO) Descriptor() ([]byte, []int) {
	return file_blc_proto_rawDescGZIP(), []int{21}
}

func (x *DcHistoryAndMessageOutputDTO) GetArgs() []*TraceStruct {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *DcHistoryAndMessageOutputDTO) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *DcHistoryAndMessageOutputDTO) GetCreatorAddress() string {
	if x != nil {
		return x.CreatorAddress
	}
	return ""
}

func (x *DcHistoryAndMessageOutputDTO) GetOwnerAddress() string {
	if x != nil {
		return x.OwnerAddress
	}
	return ""
}

func (x *DcHistoryAndMessageOutputDTO) GetDcName() string {
	if x != nil {
		return x.DcName
	}
	return ""
}

func (x *DcHistoryAndMessageOutputDTO) GetPoolId() int64 {
	if x != nil {
		return x.PoolId
	}
	return 0
}

type CreatePoolDTO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LimitAmount int64  `protobuf:"varint,1,opt,name=limit_amount,json=limitAmount,proto3" json:"limit_amount,omitempty"`
	Price       int64  `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	Amount      int64  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Cid         string `protobuf:"bytes,4,opt,name=cid,proto3" json:"cid,omitempty"`
	DcName      string `protobuf:"bytes,5,opt,name=dc_name,json=dcName,proto3" json:"dc_name,omitempty"`
}

func (x *CreatePoolDTO) Reset() {
	*x = CreatePoolDTO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blc_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePoolDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePoolDTO) ProtoMessage() {}

func (x *CreatePoolDTO) ProtoReflect() protoreflect.Message {
	mi := &file_blc_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePoolDTO.ProtoReflect.Descriptor instead.
func (*CreatePoolDTO) Descriptor() ([]byte, []int) {
	return file_blc_proto_rawDescGZIP(), []int{22}
}

func (x *CreatePoolDTO) GetLimitAmount() int64 {
	if x != nil {
		return x.LimitAmount
	}
	return 0
}

func (x *CreatePoolDTO) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreatePoolDTO) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreatePoolDTO) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *CreatePoolDTO) GetDcName() string {
	if x != nil {
		return x.DcName
	}
	return ""
}

type CreateActivityDTO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Password []byte `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Amount   int64  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Cid      string `protobuf:"bytes,4,opt,name=cid,proto3" json:"cid,omitempty"`
	DcName   string `protobuf:"bytes,5,opt,name=dc_name,json=dcName,proto3" json:"dc_name,omitempty"`
}

func (x *CreateActivityDTO) Reset() {
	*x = CreateActivityDTO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blc_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateActivityDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateActivityDTO) ProtoMessage() {}

func (x *CreateActivityDTO) ProtoReflect() protoreflect.Message {
	mi := &file_blc_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateActivityDTO.ProtoReflect.Descriptor instead.
func (*CreateActivityDTO) Descriptor() ([]byte, []int) {
	return file_blc_proto_rawDescGZIP(), []int{23}
}

func (x *CreateActivityDTO) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateActivityDTO) GetPassword() []byte {
	if x != nil {
		return x.Password
	}
	return nil
}

func (x *CreateActivityDTO) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateActivityDTO) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *CreateActivityDTO) GetDcName() string {
	if x != nil {
		return x.DcName
	}
	return ""
}

type CheckDcAndReturnTimeOutputDTO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CheckResult bool    `protobuf:"varint,1,opt,name=check_result,json=checkResult,proto3" json:"check_result,omitempty"`
	TimeList    []int64 `protobuf:"varint,2,rep,packed,name=time_list,json=timeList,proto3" json:"time_list,omitempty"`
}

func (x *CheckDcAndReturnTimeOutputDTO) Reset() {
	*x = CheckDcAndReturnTimeOutputDTO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blc_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckDcAndReturnTimeOutputDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckDcAndReturnTimeOutputDTO) ProtoMessage() {}

func (x *CheckDcAndReturnTimeOutputDTO) ProtoReflect() protoreflect.Message {
	mi := &file_blc_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckDcAndReturnTimeOutputDTO.ProtoReflect.Descriptor instead.
func (*CheckDcAndReturnTimeOutputDTO) Descriptor() ([]byte, []int) {
	return file_blc_proto_rawDescGZIP(), []int{24}
}

func (x *CheckDcAndReturnTimeOutputDTO) GetCheckResult() bool {
	if x != nil {
		return x.CheckResult
	}
	return false
}

func (x *CheckDcAndReturnTimeOutputDTO) GetTimeList() []int64 {
	if x != nil {
		return x.TimeList
	}
	return nil
}

type CheckDcAndReturnTimeDTO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Owner          string   `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	CollectionHash [][]byte `protobuf:"bytes,2,rep,name=collection_hash,json=collectionHash,proto3" json:"collection_hash,omitempty"`
}

func (x *CheckDcAndReturnTimeDTO) Reset() {
	*x = CheckDcAndReturnTimeDTO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blc_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckDcAndReturnTimeDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckDcAndReturnTimeDTO) ProtoMessage() {}

func (x *CheckDcAndReturnTimeDTO) ProtoReflect() protoreflect.Message {
	mi := &file_blc_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckDcAndReturnTimeDTO.ProtoReflect.Descriptor instead.
func (*CheckDcAndReturnTimeDTO) Descriptor() ([]byte, []int) {
	return file_blc_proto_rawDescGZIP(), []int{25}
}

func (x *CheckDcAndReturnTimeDTO) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *CheckDcAndReturnTimeDTO) GetCollectionHash() [][]byte {
	if x != nil {
		return x.CollectionHash
	}
	return nil
}

type BeforeMintDTO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DcId     int64  `protobuf:"varint,1,opt,name=dc_id,json=dcId,proto3" json:"dc_id,omitempty"`
	UniqueId []byte `protobuf:"bytes,2,opt,name=unique_id,json=uniqueId,proto3" json:"unique_id,omitempty"`
}

func (x *BeforeMintDTO) Reset() {
	*x = BeforeMintDTO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blc_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BeforeMintDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeforeMintDTO) ProtoMessage() {}

func (x *BeforeMintDTO) ProtoReflect() protoreflect.Message {
	mi := &file_blc_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeforeMintDTO.ProtoReflect.Descriptor instead.
func (*BeforeMintDTO) Descriptor() ([]byte, []int) {
	return file_blc_proto_rawDescGZIP(), []int{26}
}

func (x *BeforeMintDTO) GetDcId() int64 {
	if x != nil {
		return x.DcId
	}
	return 0
}

func (x *BeforeMintDTO) GetUniqueId() []byte {
	if x != nil {
		return x.UniqueId
	}
	return nil
}

type ActivityAndPool struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Activity *Activity `protobuf:"bytes,1,opt,name=activity,proto3" json:"activity,omitempty"`
	Pool     *Pool     `protobuf:"bytes,2,opt,name=pool,proto3" json:"pool,omitempty"`
}

func (x *ActivityAndPool) Reset() {
	*x = ActivityAndPool{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blc_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActivityAndPool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityAndPool) ProtoMessage() {}

func (x *ActivityAndPool) ProtoReflect() protoreflect.Message {
	mi := &file_blc_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityAndPool.ProtoReflect.Descriptor instead.
func (*ActivityAndPool) Descriptor() ([]byte, []int) {
	return file_blc_proto_rawDescGZIP(), []int{27}
}

func (x *ActivityAndPool) GetActivity() *Activity {
	if x != nil {
		return x.Activity
	}
	return nil
}

func (x *ActivityAndPool) GetPool() *Pool {
	if x != nil {
		return x.Pool
	}
	return nil
}

type Pool struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cid         string `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price       int64  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	Amount      int64  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Left        int64  `protobuf:"varint,5,opt,name=left,proto3" json:"left,omitempty"`
	LimitAmount int64  `protobuf:"varint,6,opt,name=limit_amount,json=limitAmount,proto3" json:"limit_amount,omitempty"`
	Creator     string `protobuf:"bytes,7,opt,name=creator,proto3" json:"creator,omitempty"`
	CreateTime  int64  `protobuf:"varint,8,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
}

func (x *Pool) Reset() {
	*x = Pool{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blc_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pool) ProtoMessage() {}

func (x *Pool) ProtoReflect() protoreflect.Message {
	mi := &file_blc_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pool.ProtoReflect.Descriptor instead.
func (*Pool) Descriptor() ([]byte, []int) {
	return file_blc_proto_rawDescGZIP(), []int{28}
}

func (x *Pool) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *Pool) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Pool) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Pool) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Pool) GetLeft() int64 {
	if x != nil {
		return x.Left
	}
	return 0
}

func (x *Pool) GetLimitAmount() int64 {
	if x != nil {
		return x.LimitAmount
	}
	return 0
}

func (x *Pool) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

func (x *Pool) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

type Dc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UniqueHash  []byte `protobuf:"bytes,1,opt,name=unique_hash,json=uniqueHash,proto3" json:"unique_hash,omitempty"`
	MintTime    int64  `protobuf:"varint,2,opt,name=mint_time,json=mintTime,proto3" json:"mint_time,omitempty"`
	PoolId      int64  `protobuf:"varint,3,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	IndexInPool int64  `protobuf:"varint,4,opt,name=index_in_pool,json=indexInPool,proto3" json:"index_in_pool,omitempty"`
}

func (x *Dc) Reset() {
	*x = Dc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blc_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Dc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dc) ProtoMessage() {}

func (x *Dc) ProtoReflect() protoreflect.Message {
	mi := &file_blc_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dc.ProtoReflect.Descriptor instead.
func (*Dc) Descriptor() ([]byte, []int) {
	return file_blc_proto_rawDescGZIP(), []int{29}
}

func (x *Dc) GetUniqueHash() []byte {
	if x != nil {
		return x.UniqueHash
	}
	return nil
}

func (x *Dc) GetMintTime() int64 {
	if x != nil {
		return x.MintTime
	}
	return 0
}

func (x *Dc) GetPoolId() int64 {
	if x != nil {
		return x.PoolId
	}
	return 0
}

func (x *Dc) GetIndexInPool() int64 {
	if x != nil {
		return x.IndexInPool
	}
	return 0
}

type Activity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	EncodedKey []byte `protobuf:"bytes,2,opt,name=encoded_key,json=encodedKey,proto3" json:"encoded_key,omitempty"`
	PoolId     int64  `protobuf:"varint,3,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
}

func (x *Activity) Reset() {
	*x = Activity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blc_proto_msgTypes[30]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Activity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Activity) ProtoMessage() {}

func (x *Activity) ProtoReflect() protoreflect.Message {
	mi := &file_blc_proto_msgTypes[30]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Activity.ProtoReflect.Descriptor instead.
func (*Activity) Descriptor() ([]byte, []int) {
	return file_blc_proto_rawDescGZIP(), []int{30}
}

func (x *Activity) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Activity) GetEncodedKey() []byte {
	if x != nil {
		return x.EncodedKey
	}
	return nil
}

func (x *Activity) GetPoolId() int64 {
	if x != nil {
		return x.PoolId
	}
	return 0
}

type TraceStruct struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sender        string `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	To            string `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	OperateTime   int64  `protobuf:"varint,3,opt,name=operate_time,json=operateTime,proto3" json:"operate_time,omitempty"`
	OperateRecord string `protobuf:"bytes,4,opt,name=operate_record,json=operateRecord,proto3" json:"operate_record,omitempty"`
}

func (x *TraceStruct) Reset() {
	*x = TraceStruct{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blc_proto_msgTypes[31]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TraceStruct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraceStruct) ProtoMessage() {}

func (x *TraceStruct) ProtoReflect() protoreflect.Message {
	mi := &file_blc_proto_msgTypes[31]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TraceStruct.ProtoReflect.Descriptor instead.
func (*TraceStruct) Descriptor() ([]byte, []int) {
	return file_blc_proto_rawDescGZIP(), []int{31}
}

func (x *TraceStruct) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *TraceStruct) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *TraceStruct) GetOperateTime() int64 {
	if x != nil {
		return x.OperateTime
	}
	return 0
}

func (x *TraceStruct) GetOperateRecord() string {
	if x != nil {
		return x.OperateRecord
	}
	return ""
}

var File_blc_proto protoreflect.FileDescriptor

var file_blc_proto_rawDesc = []byte{
	0x0a, 0x09, 0x62, 0x6c, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61, 0x70, 0x69,
	0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4b, 0x0a,
	0x0e, 0x53, 0x69, 0x67, 0x6e, 0x55, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x1f, 0x0a, 0x0b, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79,
	0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x2e, 0x0a, 0x12, 0x55, 0x73,
	0x65, 0x72, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x2f, 0x0a, 0x13, 0x55, 0x73,
	0x65, 0x72, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x22, 0x30, 0x0a, 0x16, 0x41,
	0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x6c, 0x0a,
	0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x55,
	0x73, 0x65, 0x72, 0x4b, 0x65, 0x79, 0x52, 0x07, 0x75, 0x73, 0x65, 0x72, 0x4b, 0x65, 0x79, 0x12,
	0x2a, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69,
	0x74, 0x79, 0x44, 0x54, 0x4f, 0x52, 0x04, 0x61, 0x72, 0x67, 0x73, 0x22, 0x28, 0x0a, 0x16, 0x47,
	0x65, 0x74, 0x49, 0x64, 0x54, 0x6f, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x23, 0x0a, 0x11, 0x42, 0x65, 0x66, 0x6f, 0x72, 0x65, 0x4d,
	0x69, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x69, 0x0a, 0x18, 0x47, 0x65,
	0x74, 0x44, 0x63, 0x46, 0x72, 0x6f, 0x6d, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x4b, 0x65,
	0x79, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2d, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x63,
	0x46, 0x72, 0x6f, 0x6d, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x44, 0x54, 0x4f, 0x52,
	0x04, 0x61, 0x72, 0x67, 0x73, 0x22, 0x2a, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x61, 0x73,
	0x68, 0x22, 0x2c, 0x0a, 0x12, 0x55, 0x73, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22,
	0x4d, 0x0a, 0x1b, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x44, 0x63, 0x41, 0x6e, 0x64, 0x52, 0x65, 0x74,
	0x75, 0x72, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2e,
	0x0a, 0x03, 0x64, 0x74, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x44, 0x63, 0x41, 0x6e, 0x64, 0x52, 0x65, 0x74, 0x75,
	0x72, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x44, 0x54, 0x4f, 0x52, 0x03, 0x64, 0x74, 0x6f, 0x22, 0x2a,
	0x0a, 0x14, 0x47, 0x65, 0x74, 0x48, 0x61, 0x73, 0x68, 0x54, 0x6f, 0x44, 0x63, 0x49, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x22, 0x2c, 0x0a, 0x15, 0x47, 0x65,
	0x74, 0x48, 0x61, 0x73, 0x68, 0x54, 0x6f, 0x44, 0x63, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x13, 0x0a, 0x05, 0x64, 0x63, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x64, 0x63, 0x49, 0x64, 0x22, 0x35, 0x0a, 0x0b, 0x47, 0x69, 0x76, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x07, 0x67, 0x69, 0x76, 0x65, 0x44,
	0x54, 0x4f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47,
	0x69, 0x76, 0x65, 0x44, 0x54, 0x4f, 0x52, 0x07, 0x67, 0x69, 0x76, 0x65, 0x44, 0x54, 0x4f, 0x22,
	0x2f, 0x0a, 0x1d, 0x47, 0x65, 0x74, 0x44, 0x63, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x41,
	0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x2c, 0x0a, 0x12, 0x50, 0x6f, 0x6f, 0x6c, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x62,
	0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x55, 0x73, 0x65, 0x72,
	0x4b, 0x65, 0x79, 0x52, 0x07, 0x75, 0x73, 0x65, 0x72, 0x4b, 0x65, 0x79, 0x12, 0x24, 0x0a, 0x03,
	0x64, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x6f, 0x6c, 0x44, 0x54, 0x4f, 0x52, 0x03, 0x64,
	0x74, 0x6f, 0x22, 0x4f, 0x0a, 0x0b, 0x4d, 0x69, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x27, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x4b, 0x65,
	0x79, 0x52, 0x07, 0x75, 0x73, 0x65, 0x72, 0x4b, 0x65, 0x79, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x6f,
	0x6f, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x70, 0x6f, 0x6f,
	0x6c, 0x49, 0x64, 0x22, 0x24, 0x0a, 0x07, 0x55, 0x73, 0x65, 0x72, 0x4b, 0x65, 0x79, 0x12, 0x19,
	0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x75, 0x73, 0x65, 0x72, 0x4b, 0x65, 0x79, 0x22, 0x3d, 0x0a, 0x07, 0x47, 0x69, 0x76,
	0x65, 0x44, 0x54, 0x4f, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x6f, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x6f, 0x41, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x12, 0x13, 0x0a, 0x05, 0x64, 0x63, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x64, 0x63, 0x49, 0x64, 0x22, 0x53, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x44,
	0x63, 0x46, 0x72, 0x6f, 0x6d, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x44, 0x54, 0x4f,
	0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x49,
	0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0xd8, 0x01,
	0x0a, 0x1c, 0x44, 0x63, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x41, 0x6e, 0x64, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x44, 0x54, 0x4f, 0x12, 0x24,
	0x0a, 0x04, 0x61, 0x72, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x54, 0x72, 0x61, 0x63, 0x65, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x04,
	0x61, 0x72, 0x67, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x12, 0x27, 0x0a, 0x0f, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x6f, 0x72, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0e, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x12, 0x23, 0x0a, 0x0d, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x64, 0x63, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x63, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x17, 0x0a, 0x07, 0x70, 0x6f, 0x6f, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x70, 0x6f, 0x6f, 0x6c, 0x49, 0x64, 0x22, 0x8b, 0x01, 0x0a, 0x0d, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x50, 0x6f, 0x6f, 0x6c, 0x44, 0x54, 0x4f, 0x12, 0x21, 0x0a, 0x0c, 0x6c, 0x69,
	0x6d, 0x69, 0x74, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0b, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x70, 0x72,
	0x69, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x63,
	0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x63, 0x69, 0x64, 0x12, 0x17, 0x0a,
	0x07, 0x64, 0x63, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x64, 0x63, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x86, 0x01, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x44, 0x54, 0x4f, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x61, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x63, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x64, 0x63, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x63, 0x4e, 0x61, 0x6d, 0x65, 0x22,
	0x5f, 0x0a, 0x1d, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x44, 0x63, 0x41, 0x6e, 0x64, 0x52, 0x65, 0x74,
	0x75, 0x72, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x44, 0x54, 0x4f,
	0x12, 0x21, 0x0a, 0x0c, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x5f, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x6c, 0x69, 0x73, 0x74,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x03, 0x52, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x4c, 0x69, 0x73, 0x74,
	0x22, 0x58, 0x0a, 0x17, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x44, 0x63, 0x41, 0x6e, 0x64, 0x52, 0x65,
	0x74, 0x75, 0x72, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x44, 0x54, 0x4f, 0x12, 0x14, 0x0a, 0x05, 0x6f,
	0x77, 0x6e, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x77, 0x6e, 0x65,
	0x72, 0x12, 0x27, 0x0a, 0x0f, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x68, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x0e, 0x63, 0x6f, 0x6c, 0x6c,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x61, 0x73, 0x68, 0x22, 0x41, 0x0a, 0x0d, 0x42, 0x65,
	0x66, 0x6f, 0x72, 0x65, 0x4d, 0x69, 0x6e, 0x74, 0x44, 0x54, 0x4f, 0x12, 0x13, 0x0a, 0x05, 0x64,
	0x63, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x64, 0x63, 0x49, 0x64,
	0x12, 0x1b, 0x0a, 0x09, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x08, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x49, 0x64, 0x22, 0x5b, 0x0a,
	0x0f, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x41, 0x6e, 0x64, 0x50, 0x6f, 0x6f, 0x6c,
	0x12, 0x29, 0x0a, 0x08, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74,
	0x79, 0x52, 0x08, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x12, 0x1d, 0x0a, 0x04, 0x70,
	0x6f, 0x6f, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x50, 0x6f, 0x6f, 0x6c, 0x52, 0x04, 0x70, 0x6f, 0x6f, 0x6c, 0x22, 0xcc, 0x01, 0x0a, 0x04, 0x50,
	0x6f, 0x6f, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x63, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69,
	0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x65, 0x66, 0x74, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x6c, 0x65, 0x66, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x6c,
	0x69, 0x6d, 0x69, 0x74, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0b, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x18,
	0x0a, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x7f, 0x0a, 0x02, 0x44, 0x63, 0x12,
	0x1f, 0x0a, 0x0b, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x48, 0x61, 0x73, 0x68,
	0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x69, 0x6e, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x08, 0x6d, 0x69, 0x6e, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x17, 0x0a,
	0x07, 0x70, 0x6f, 0x6f, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x70, 0x6f, 0x6f, 0x6c, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0d, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x5f,
	0x69, 0x6e, 0x5f, 0x70, 0x6f, 0x6f, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x69,
	0x6e, 0x64, 0x65, 0x78, 0x49, 0x6e, 0x50, 0x6f, 0x6f, 0x6c, 0x22, 0x58, 0x0a, 0x08, 0x41, 0x63,
	0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x65, 0x6e,
	0x63, 0x6f, 0x64, 0x65, 0x64, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x0a, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x64, 0x4b, 0x65, 0x79, 0x12, 0x17, 0x0a, 0x07, 0x70,
	0x6f, 0x6f, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x70, 0x6f,
	0x6f, 0x6c, 0x49, 0x64, 0x22, 0x7f, 0x0a, 0x0b, 0x54, 0x72, 0x61, 0x63, 0x65, 0x53, 0x74, 0x72,
	0x75, 0x63, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x74,
	0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x74, 0x6f, 0x12, 0x21, 0x0a, 0x0c, 0x6f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0b, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x25,
	0x0a, 0x0e, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x5f, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x32, 0x97, 0x08, 0x0a, 0x0d, 0x42, 0x6c, 0x63, 0x52, 0x70, 0x63,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x35, 0x0a, 0x06, 0x53, 0x69, 0x67, 0x6e, 0x55,
	0x70, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x13, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x53, 0x69, 0x67, 0x6e, 0x55, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x43,
	0x0a, 0x0e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65,
	0x12, 0x17, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x42, 0x61, 0x6c, 0x61, 0x6e,
	0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x55, 0x73, 0x65, 0x72, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x48, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69,
	0x74, 0x79, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x1a, 0x1b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x41,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x44, 0x0a,
	0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x12,
	0x1a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x63, 0x74, 0x69,
	0x76, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x12, 0x44, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x49, 0x64, 0x54, 0x6f, 0x41, 0x63,
	0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x12, 0x1b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74,
	0x49, 0x64, 0x54, 0x6f, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69,
	0x74, 0x79, 0x41, 0x6e, 0x64, 0x50, 0x6f, 0x6f, 0x6c, 0x12, 0x38, 0x0a, 0x0a, 0x42, 0x65, 0x66,
	0x6f, 0x72, 0x65, 0x4d, 0x69, 0x6e, 0x74, 0x12, 0x16, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x42, 0x65,
	0x66, 0x6f, 0x72, 0x65, 0x4d, 0x69, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x12, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x42, 0x65, 0x66, 0x6f, 0x72, 0x65, 0x4d, 0x69, 0x6e, 0x74,
	0x44, 0x54, 0x4f, 0x12, 0x4a, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x44, 0x63, 0x46, 0x72, 0x6f, 0x6d,
	0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x12, 0x1d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47,
	0x65, 0x74, 0x44, 0x63, 0x46, 0x72, 0x6f, 0x6d, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12,
	0x43, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x19, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5c, 0x0a, 0x14, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x44, 0x63, 0x41,
	0x6e, 0x64, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x20, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x44, 0x63, 0x41, 0x6e, 0x64, 0x52, 0x65, 0x74,
	0x75, 0x72, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x44, 0x63, 0x41, 0x6e, 0x64, 0x52,
	0x65, 0x74, 0x75, 0x72, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x44,
	0x54, 0x4f, 0x12, 0x46, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x48, 0x61, 0x73, 0x68, 0x54, 0x6f, 0x44,
	0x63, 0x49, 0x64, 0x12, 0x19, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x48, 0x61, 0x73,
	0x68, 0x54, 0x6f, 0x44, 0x63, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x48, 0x61, 0x73, 0x68, 0x54, 0x6f, 0x44, 0x63,
	0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x04, 0x47, 0x69,
	0x76, 0x65, 0x12, 0x10, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x69, 0x76, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x5f, 0x0a, 0x16,
	0x47, 0x65, 0x74, 0x44, 0x63, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x41, 0x6e, 0x64, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x22, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74,
	0x44, 0x63, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x41, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x44, 0x63, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x41, 0x6e, 0x64, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x44, 0x54, 0x4f, 0x12, 0x40, 0x0a,
	0x0d, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x6f, 0x6c, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x16,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x17, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x6f, 0x6f,
	0x6c, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x3c, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x6f, 0x6c, 0x12, 0x16, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x6f, 0x6c, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x30, 0x0a,
	0x04, 0x4d, 0x69, 0x6e, 0x74, 0x12, 0x10, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x69, 0x6e, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x42,
	0x08, 0x5a, 0x06, 0x2e, 0x2f, 0x3b, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_blc_proto_rawDescOnce sync.Once
	file_blc_proto_rawDescData = file_blc_proto_rawDesc
)

func file_blc_proto_rawDescGZIP() []byte {
	file_blc_proto_rawDescOnce.Do(func() {
		file_blc_proto_rawDescData = protoimpl.X.CompressGZIP(file_blc_proto_rawDescData)
	})
	return file_blc_proto_rawDescData
}

var file_blc_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_blc_proto_goTypes = []interface{}{
	(*SignUpResponse)(nil),                // 0: api.SignUpResponse
	(*UserBalanceRequest)(nil),            // 1: api.UserBalanceRequest
	(*UserBalanceResponse)(nil),           // 2: api.UserBalanceResponse
	(*ActivityAmountResponse)(nil),        // 3: api.ActivityAmountResponse
	(*CreateActivityRequest)(nil),         // 4: api.CreateActivityRequest
	(*GetIdToActivityRequest)(nil),        // 5: api.GetIdToActivityRequest
	(*BeforeMintRequest)(nil),             // 6: api.BeforeMintRequest
	(*GetDcFromActivityRequest)(nil),      // 7: api.GetDcFromActivityRequest
	(*GetUserStatusRequest)(nil),          // 8: api.GetUserStatusRequest
	(*UserStatusResponse)(nil),            // 9: api.UserStatusResponse
	(*CheckDcAndReturnTimeRequest)(nil),   // 10: api.CheckDcAndReturnTimeRequest
	(*GetHashToDcIdRequest)(nil),          // 11: api.GetHashToDcIdRequest
	(*GetHashToDcIdResponse)(nil),         // 12: api.GetHashToDcIdResponse
	(*GiveRequest)(nil),                   // 13: api.GiveRequest
	(*GetDcHistoryAndMessageRequest)(nil), // 14: api.GetDcHistoryAndMessageRequest
	(*PoolAmountResponse)(nil),            // 15: api.PoolAmountResponse
	(*CreatePoolRequest)(nil),             // 16: api.CreatePoolRequest
	(*MintRequest)(nil),                   // 17: api.MintRequest
	(*UserKey)(nil),                       // 18: api.UserKey
	(*GiveDTO)(nil),                       // 19: api.GiveDTO
	(*GetDcFromActivityDTO)(nil),          // 20: api.GetDcFromActivityDTO
	(*DcHistoryAndMessageOutputDTO)(nil),  // 21: api.DcHistoryAndMessageOutputDTO
	(*CreatePoolDTO)(nil),                 // 22: api.CreatePoolDTO
	(*CreateActivityDTO)(nil),             // 23: api.CreateActivityDTO
	(*CheckDcAndReturnTimeOutputDTO)(nil), // 24: api.CheckDcAndReturnTimeOutputDTO
	(*CheckDcAndReturnTimeDTO)(nil),       // 25: api.CheckDcAndReturnTimeDTO
	(*BeforeMintDTO)(nil),                 // 26: api.BeforeMintDTO
	(*ActivityAndPool)(nil),               // 27: api.ActivityAndPool
	(*Pool)(nil),                          // 28: api.Pool
	(*Dc)(nil),                            // 29: api.Dc
	(*Activity)(nil),                      // 30: api.Activity
	(*TraceStruct)(nil),                   // 31: api.TraceStruct
	(*emptypb.Empty)(nil),                 // 32: google.protobuf.Empty
}
var file_blc_proto_depIdxs = []int32{
	18, // 0: api.CreateActivityRequest.user_key:type_name -> api.UserKey
	23, // 1: api.CreateActivityRequest.args:type_name -> api.CreateActivityDTO
	18, // 2: api.GetDcFromActivityRequest.key:type_name -> api.UserKey
	20, // 3: api.GetDcFromActivityRequest.args:type_name -> api.GetDcFromActivityDTO
	25, // 4: api.CheckDcAndReturnTimeRequest.dto:type_name -> api.CheckDcAndReturnTimeDTO
	19, // 5: api.GiveRequest.giveDTO:type_name -> api.GiveDTO
	18, // 6: api.CreatePoolRequest.user_key:type_name -> api.UserKey
	22, // 7: api.CreatePoolRequest.dto:type_name -> api.CreatePoolDTO
	18, // 8: api.MintRequest.user_key:type_name -> api.UserKey
	31, // 9: api.DcHistoryAndMessageOutputDTO.args:type_name -> api.TraceStruct
	30, // 10: api.ActivityAndPool.activity:type_name -> api.Activity
	28, // 11: api.ActivityAndPool.pool:type_name -> api.Pool
	32, // 12: api.BlcRpcService.SignUp:input_type -> google.protobuf.Empty
	1,  // 13: api.BlcRpcService.GetUserBalance:input_type -> api.UserBalanceRequest
	32, // 14: api.BlcRpcService.GetActivityAmount:input_type -> google.protobuf.Empty
	4,  // 15: api.BlcRpcService.CreateActivity:input_type -> api.CreateActivityRequest
	5,  // 16: api.BlcRpcService.GetIdToActivity:input_type -> api.GetIdToActivityRequest
	6,  // 17: api.BlcRpcService.BeforeMint:input_type -> api.BeforeMintRequest
	7,  // 18: api.BlcRpcService.GetDcFromActivity:input_type -> api.GetDcFromActivityRequest
	8,  // 19: api.BlcRpcService.GetUserStatus:input_type -> api.GetUserStatusRequest
	10, // 20: api.BlcRpcService.CheckDcAndReturnTime:input_type -> api.CheckDcAndReturnTimeRequest
	11, // 21: api.BlcRpcService.GetHashToDcId:input_type -> api.GetHashToDcIdRequest
	13, // 22: api.BlcRpcService.Give:input_type -> api.GiveRequest
	14, // 23: api.BlcRpcService.GetDcHistoryAndMessage:input_type -> api.GetDcHistoryAndMessageRequest
	32, // 24: api.BlcRpcService.GetPoolAmount:input_type -> google.protobuf.Empty
	16, // 25: api.BlcRpcService.CreatePool:input_type -> api.CreatePoolRequest
	17, // 26: api.BlcRpcService.Mint:input_type -> api.MintRequest
	0,  // 27: api.BlcRpcService.SignUp:output_type -> api.SignUpResponse
	2,  // 28: api.BlcRpcService.GetUserBalance:output_type -> api.UserBalanceResponse
	3,  // 29: api.BlcRpcService.GetActivityAmount:output_type -> api.ActivityAmountResponse
	32, // 30: api.BlcRpcService.CreateActivity:output_type -> google.protobuf.Empty
	27, // 31: api.BlcRpcService.GetIdToActivity:output_type -> api.ActivityAndPool
	26, // 32: api.BlcRpcService.BeforeMint:output_type -> api.BeforeMintDTO
	32, // 33: api.BlcRpcService.GetDcFromActivity:output_type -> google.protobuf.Empty
	9,  // 34: api.BlcRpcService.GetUserStatus:output_type -> api.UserStatusResponse
	24, // 35: api.BlcRpcService.CheckDcAndReturnTime:output_type -> api.CheckDcAndReturnTimeOutputDTO
	12, // 36: api.BlcRpcService.GetHashToDcId:output_type -> api.GetHashToDcIdResponse
	32, // 37: api.BlcRpcService.Give:output_type -> google.protobuf.Empty
	21, // 38: api.BlcRpcService.GetDcHistoryAndMessage:output_type -> api.DcHistoryAndMessageOutputDTO
	15, // 39: api.BlcRpcService.GetPoolAmount:output_type -> api.PoolAmountResponse
	32, // 40: api.BlcRpcService.CreatePool:output_type -> google.protobuf.Empty
	32, // 41: api.BlcRpcService.Mint:output_type -> google.protobuf.Empty
	27, // [27:42] is the sub-list for method output_type
	12, // [12:27] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_blc_proto_init() }
func file_blc_proto_init() {
	if File_blc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_blc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignUpResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserBalanceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserBalanceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActivityAmountResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blc_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateActivityRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blc_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetIdToActivityRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blc_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BeforeMintRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blc_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDcFromActivityRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blc_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blc_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserStatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blc_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckDcAndReturnTimeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blc_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHashToDcIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blc_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHashToDcIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blc_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GiveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blc_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDcHistoryAndMessageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blc_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PoolAmountResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blc_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePoolRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blc_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MintRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blc_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blc_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GiveDTO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blc_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDcFromActivityDTO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blc_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DcHistoryAndMessageOutputDTO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blc_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePoolDTO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blc_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateActivityDTO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blc_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckDcAndReturnTimeOutputDTO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blc_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckDcAndReturnTimeDTO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blc_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BeforeMintDTO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blc_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActivityAndPool); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blc_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pool); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blc_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Dc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blc_proto_msgTypes[30].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Activity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blc_proto_msgTypes[31].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TraceStruct); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_blc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_blc_proto_goTypes,
		DependencyIndexes: file_blc_proto_depIdxs,
		MessageInfos:      file_blc_proto_msgTypes,
	}.Build()
	File_blc_proto = out.File
	file_blc_proto_rawDesc = nil
	file_blc_proto_goTypes = nil
	file_blc_proto_depIdxs = nil
}
