cryptoMaterial:
  certPath: "conf"
  caCert: "conf/ca.crt"
  sslCert: "conf/sdk.crt"
  sslKey: "conf/sdk.key"
#  enSslCert: "conf/gm/gmensdk.crt"
#  enSslKey: "conf/gm/gmensdk.key"

network:
  peers:
    - "10.21.32.192:20200"

amop:
#  - publicKeys: [ "conf/amop/consumer_public_key_1.pem" ]
#    topicName: "PrivateTopic1"
#  - password: "123456"
#    privateKey: "conf/amop/consumer_private_key.p12"
#    topicName: "PrivateTopic2"


#  password: ""


threadPool:
  channelProcessorThreadSize: "16"
  receiptProcessorThreadSize: "16"
  maxBlockingQueueSize: "102400"